import { Category, Helpline, ServiceLink } from './types';

export const CATEGORY_CONFIG: Category[] = [
  {
    id: 'all',
    title: 'All Services',
    iconName: 'layout-grid',
    gradient: 'from-slate-700 to-slate-900',
    accentColor: '#334155',
    description: 'Comprehensive directory of all verified Indian government portals and citizen services.',
  },
  {
    id: 'identity',
    title: 'Identity & Citizen',
    iconName: 'user-check',
    gradient: 'from-blue-600 to-indigo-700',
    accentColor: '#2563EB',
    description: 'Aadhaar, Passport, PAN, Voter ID, DigiLocker, RTI, and vital certificate portals.',
  },
  {
    id: 'finance',
    title: 'Finance & Taxes',
    iconName: 'landmark',
    gradient: 'from-emerald-600 to-teal-700',
    accentColor: '#059669',
    description: 'Income Tax e-Filing, GST, EPFO PF balances, NPS, Corporate MCA21, and Banking.',
  },
  {
    id: 'agriculture',
    title: 'Agriculture & Rural',
    iconName: 'sprout',
    gradient: 'from-lime-600 to-emerald-700',
    accentColor: '#65A30D',
    description: 'PM-KISAN, Kisan Suvidha, Soil Health, e-NAM mandi prices, Crop Insurance, and MGNREGA.',
  },
  {
    id: 'health',
    title: 'Health & Ayushman',
    iconName: 'heart-pulse',
    gradient: 'from-rose-500 to-red-700',
    accentColor: '#E11D48',
    description: 'Ayushman ABHA ID, PM-JAY cards, eSanjeevani Tele-consultation, Jan Aushadhi, and Blood banks.',
  },
  {
    id: 'land',
    title: 'Land Records & Property',
    iconName: 'map-pin',
    gradient: 'from-amber-600 to-orange-700',
    accentColor: '#D97706',
    description: 'State-wise digital 7/12, RoR, Bhulekh, Dharani, Bhoomi, Patta Chitta, and Property registration.',
  },
  {
    id: 'education',
    title: 'Education & Careers',
    iconName: 'graduation-cap',
    gradient: 'from-violet-600 to-purple-800',
    accentColor: '#7C3AED',
    description: 'National Scholarships, SWAYAM courses, NTA Exam portals, Skill India, and e-Shram.',
  },
  {
    id: 'travel',
    title: 'Travel & Transport',
    iconName: 'train',
    gradient: 'from-cyan-600 to-blue-700',
    accentColor: '#0891B2',
    description: 'Parivahan Driving Licenses, Vehicle RC, IRCTC Train Booking, FASTag, and e-Challan.',
  },
  {
    id: 'utilities',
    title: 'Utilities, Safety & Law',
    iconName: 'shield-alert',
    gradient: 'from-orange-600 to-red-700',
    accentColor: '#EA580C',
    description: 'Cyber Crime Reporting, Sanchar Saathi lost phones, Rooftop Solar, LPG cylinders, and e-Courts.',
  },
  {
    id: 'welfare',
    title: 'Housing & Welfare',
    iconName: 'home',
    gradient: 'from-pink-600 to-rose-700',
    accentColor: '#DB2777',
    description: 'PM Awas Yojana (PMAY), Jal Jeevan Mission, PM Ujjwala LPG, UDID Disability Cards, and Pensions.',
  },
];

export const SERVICE_DATA: ServiceLink[] = [
  // ==========================================
  // IDENTITY & CITIZEN SERVICES
  // ==========================================
  {
    id: 'aadhaar',
    title: 'UIDAI myAadhaar Portal',
    description: 'Download e-Aadhaar, update demographic details, lock/unlock biometrics, and check PVC card status.',
    url: 'https://myaadhaar.uidai.gov.in/',
    iconName: 'fingerprint',
    categoryId: 'identity',
    department: 'Unique Identification Authority of India (UIDAI)',
    tags: ['aadhaar', 'uidai', 'biometrics', 'pvc card', 'identity', 'update address', 'download aadhaar'],
    features: ['Download e-Aadhaar PDF', 'Demographic Address Update', 'Lock/Unlock Biometrics', 'Order Aadhaar PVC Card'],
    badge: 'Essential',
  },
  {
    id: 'passport',
    title: 'Passport Seva Online',
    description: 'Apply for fresh or renewal passports, police clearance certificates, track status, and book appointment slots.',
    url: 'https://www.passportindia.gov.in/',
    iconName: 'plane',
    categoryId: 'identity',
    department: 'Ministry of External Affairs (CPV Division)',
    tags: ['passport', 'tatkaal', 'pcc', 'visa', 'travel', 'mea', 'appointment'],
    features: ['Fresh Passport Application', 'Passport Re-issue/Renewal', 'Police Clearance Certificate (PCC)', 'Appointment Slot Booking'],
    badge: 'Essential',
  },
  {
    id: 'digilocker',
    title: 'DigiLocker Digital Wallet',
    description: 'Legally valid cloud storage for driving licenses, vehicle RCs, Aadhaar, marks sheets, and insurance policies.',
    url: 'https://www.digilocker.gov.in/',
    iconName: 'folder-lock',
    categoryId: 'identity',
    department: 'Ministry of Electronics and Information Technology (MeitY)',
    tags: ['digilocker', 'documents', 'driving license', 'cbse marksheet', 'rc', 'cloud', 'digital india'],
    features: ['Instant Authentic Documents Issuance', 'Legally Equivalent to Originals per IT Act', 'Aadhaar, RC & DL Integration', '1GB Secure Cloud Storage'],
    badge: 'Essential',
  },
  {
    id: 'pan-nsdl',
    title: 'NSDL PAN Card Portal',
    description: 'Apply for new Permanent Account Number (PAN), corrections in existing PAN data, or reprint physical cards.',
    url: 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html',
    iconName: 'credit-card',
    categoryId: 'identity',
    department: 'Income Tax Department (Protean / NSDL)',
    tags: ['pan card', 'nsdl', 'protean', 'tax id', 'pan correction', 'reprint pan'],
    features: ['New PAN Application (Form 49A)', 'PAN Data Correction', 'Reprint Physical PAN Card', 'Instant e-PAN Download'],
    badge: 'Popular',
  },
  {
    id: 'voter-portal',
    title: 'ECI Voters Service Portal',
    description: 'Register as a new voter (Form 6), download digital e-EPIC card, check name in electoral roll, and update address.',
    url: 'https://voters.eci.gov.in/',
    iconName: 'vote',
    categoryId: 'identity',
    department: 'Election Commission of India (ECI)',
    tags: ['voter id', 'eci', 'e-epic', 'election', 'electoral roll', 'form 6', 'polling station'],
    features: ['New Voter Registration (Form 6)', 'Download e-EPIC Digital Voter Card', 'Search Name in Electoral Roll', 'Shift Residence Correction (Form 8)'],
    badge: 'Popular',
  },
  {
    id: 'rti-online',
    title: 'RTI Online Portal',
    description: 'File Right to Information (RTI) applications and first appeals across Central Ministries and Departments.',
    url: 'https://rtionline.gov.in/',
    iconName: 'file-text',
    categoryId: 'identity',
    department: 'Department of Personnel and Training (DoPT)',
    tags: ['rti', 'right to information', 'governance', 'transparency', 'appeals'],
    features: ['File New Online RTI Request', 'File First Appeal', 'Online Fee Payment (₹10)', 'Track Application Status'],
  },
  {
    id: 'mygov',
    title: 'MyGov Citizen Engagement',
    description: 'Official citizen engagement platform to share governance ideas, participate in national polls, and join public initiatives.',
    url: 'https://www.mygov.in/',
    iconName: 'users',
    categoryId: 'identity',
    department: 'Digital India Corporation / MeitY',
    tags: ['mygov', 'citizen', 'volunteering', 'surveys', 'contests', 'quizzes'],
    features: ['Participate in Policy Feedback', 'Citizen Quizzes & Contests', 'Digital Volunteer Platform', 'Direct Updates from Govt'],
  },
  {
    id: 'cpgrams',
    title: 'CPGRAMS Public Grievance',
    description: 'Centralised Public Grievance Redress and Monitoring System for complaints against central and state government departments.',
    url: 'https://pgportal.gov.in/',
    iconName: 'message-square-warning',
    categoryId: 'identity',
    department: 'Department of Administrative Reforms and Public Grievances (DARPG)',
    tags: ['grievance', 'complaints', 'cpgrams', 'darpg', 'redressal', 'appeal'],
    features: ['Lodge Citizen Grievance Online', 'Track Real-time Resolution Status', 'File Appellate Review', 'Direct Ministry Monitoring'],
    badge: 'Popular',
  },
  {
    id: 'jeevan-pramaan',
    title: 'Jeevan Pramaan (Life Certificate)',
    description: 'Digital Life Certificate service for Central, State, and Defense pensioners using biometric or face authentication.',
    url: 'https://jeevanpramaan.gov.in/',
    iconName: 'award',
    categoryId: 'identity',
    department: 'Ministry of Electronics and Information Technology',
    tags: ['pension', 'life certificate', 'jeevan pramaan', 'senior citizen', 'biometric'],
    features: ['Digital Life Certificate Generation', 'Face Authentication on Smartphone', 'Instant Submission to Pension Disbursing Agency'],
  },
  {
    id: 'crs-birth-death',
    title: 'Civil Registration (CRS) Portal',
    description: 'Online registration and verification of Birth and Death certificates under the Registrar General of India.',
    url: 'https://crsorgi.gov.in/',
    iconName: 'file-check',
    categoryId: 'identity',
    department: 'Office of the Registrar General & Census Commissioner',
    tags: ['birth certificate', 'death certificate', 'crs', 'vital statistics', 'rgi'],
    features: ['Register Birth and Death Records', 'Verify Certificate Legitimacy', 'Hospital Reporting System'],
  },

  // ==========================================
  // FINANCE, TAXES & BANKING
  // ==========================================
  {
    id: 'incometax',
    title: 'Income Tax e-Filing Portal',
    description: 'File Annual Income Tax Returns (ITR 1-4), check refund status, verify Form 26AS/AIS, and link PAN with Aadhaar.',
    url: 'https://www.incometax.gov.in/iec/foportal/',
    iconName: 'receipt',
    categoryId: 'finance',
    department: 'Income Tax Department, Ministry of Finance',
    tags: ['income tax', 'itr', 'tax return', '26as', 'ais', 'tax refund', 'pan aadhaar link'],
    features: ['File Instant ITR 1/2/3/4', 'Download AIS & Form 26AS', 'Check Tax Refund Status', 'Link Aadhaar to PAN'],
    badge: 'Essential',
  },
  {
    id: 'epfo',
    title: 'EPFO Member Passbook & UAN',
    description: 'Check Provident Fund (PF) balance passbook, submit online withdrawal claims, and manage Universal Account Number (UAN).',
    url: 'https://unifiedportal-mem.epfindia.gov.in/memberinterface/',
    iconName: 'wallet',
    categoryId: 'finance',
    department: 'Employees Provident Fund Organisation (EPFO)',
    tags: ['pf', 'epfo', 'uan', 'provident fund', 'pf withdrawal', 'pension', 'passbook'],
    features: ['Check Monthly PF Balance Passbook', 'Submit Online PF Advance / Full Claim', 'Update KYC & Nominee Details', 'Transfer PF between Employers'],
    badge: 'Essential',
  },
  {
    id: 'gst',
    title: 'Goods & Services Tax (GST) Portal',
    description: 'National portal for GST registration, return filing (GSTR-1, GSTR-3B), e-Way Bill generation, and input tax credits.',
    url: 'https://www.gst.gov.in/',
    iconName: 'percent',
    categoryId: 'finance',
    department: 'GST Council / CBIC, Ministry of Finance',
    tags: ['gst', 'gstr-1', 'gstr-3b', 'indirect tax', 'e-way bill', 'business tax', 'itc'],
    features: ['GST Registration & Amendments', 'File Monthly & Annual GST Returns', 'Challan Creation & Tax Payment', 'Track Application & Refund Status'],
    badge: 'Essential',
  },
  {
    id: 'nps-trust',
    title: 'National Pension System (eNPS)',
    description: 'Open Tier I & II NPS accounts online, make contributions, switch investment schemes, and manage retirement corpus.',
    url: 'https://enps.nsdl.com/eNPS/NationalPensionSystem.html',
    iconName: 'piggy-bank',
    categoryId: 'finance',
    department: 'Pension Fund Regulatory and Development Authority (PFRDA)',
    tags: ['nps', 'pension', 'retirement', 'pfrda', 'tax saving 80ccd', 'pran'],
    features: ['Open Instant PRAN Account with Aadhaar', 'Online Tier-1 & Tier-2 Contributions', 'Scheme & Fund Manager Switching', '80CCD(1B) Tax Deduction Receipts'],
    badge: 'Popular',
  },
  {
    id: 'mca-services',
    title: 'MCA21 Company & LLP Portal',
    description: 'Register Private Limited companies, file annual statutory returns (AOC-4, MGT-7), check Director DIN, and master data.',
    url: 'https://www.mca.gov.in/',
    iconName: 'building-2',
    categoryId: 'finance',
    department: 'Ministry of Corporate Affairs (MCA)',
    tags: ['mca', 'company registration', 'llp', 'din', 'roc', 'corporate affairs'],
    features: ['Company Incorporation (SPICe+)', 'Director Identification Number (DIN)', 'View Company Master Data', 'File Annual MCA Returns'],
  },
  {
    id: 'jan-samarth',
    title: 'Jan Samarth Credit Portal',
    description: 'Unified digital portal connecting citizens to 13+ credit-linked government loan schemes (MUDRA, Education, Agriculture).',
    url: 'https://www.jansamarth.in/',
    iconName: 'coins',
    categoryId: 'finance',
    department: 'Department of Financial Services, Ministry of Finance',
    tags: ['loans', 'jan samarth', 'mudra loan', 'education loan', 'subsidy', 'credit'],
    features: ['Digital In-Principle Loan Approval', 'Access to 13+ Govt Loan Schemes', 'Direct Bank Integration', 'Automated Eligibility Check'],
    badge: 'Popular',
  },
  {
    id: 'rbi-retail-direct',
    title: 'RBI Retail Direct (Govt Bonds)',
    description: 'Invest directly in Government Securities (G-Secs), Treasury Bills (T-Bills), and Sovereign Gold Bonds with zero brokerage.',
    url: 'https://rbiretaildirect.org.in/',
    iconName: 'trending-up',
    categoryId: 'finance',
    department: 'Reserve Bank of India (RBI)',
    tags: ['rbi', 'g-secs', 'sovereign gold bonds', 'sgb', 'treasury bills', 'investment'],
    features: ['Zero Fee G-Sec Trading Account', 'Buy Sovereign Gold Bonds (SGB)', 'Invest in 91/182/364 Day T-Bills', 'Direct Primary Auction Bidding'],
  },
  {
    id: 'traces-tds',
    title: 'TRACES TDS/TCS Portal',
    description: 'Download TDS Certificate Form 16/16A, request corrections, and view Tax Credit Statements for deductors and taxpayers.',
    url: 'https://contents.tdscpc.gov.in/',
    iconName: 'file-spreadsheet',
    categoryId: 'finance',
    department: 'Central Board of Direct Taxes (CBDT)',
    tags: ['traces', 'tds', 'form 16', 'form 16a', 'tax deduction', 'cbdt'],
    features: ['Download Form 16 & Form 16A', 'TDS Return Correction Requests', 'View TDS Statement Status'],
  },
  {
    id: 'pm-svanidhi',
    title: 'PM SVANidhi Street Vendor Loan',
    description: 'Micro-credit facility offering collateral-free working capital loans of ₹10,000 to ₹50,000 for urban street vendors.',
    url: 'https://pmsvanidhi.mohua.gov.in/',
    iconName: 'store',
    categoryId: 'finance',
    department: 'Ministry of Housing and Urban Affairs (MoHUA)',
    tags: ['svanidhi', 'street vendors', 'micro loan', 'working capital', 'subsidy'],
    features: ['Apply for ₹10k/20k/50k Loans', '7% Interest Subsidy on Timely Repayment', 'Cashback on Digital Transactions'],
  },

  // ==========================================
  // AGRICULTURE, FARMING & RURAL
  // ==========================================
  {
    id: 'pmkisan',
    title: 'PM-KISAN Samman Nidhi',
    description: 'Direct income support of ₹6,000/year for landholding farmer families in three 4-monthly instalments of ₹2,000.',
    url: 'https://pmkisan.gov.in/',
    iconName: 'sprout',
    categoryId: 'agriculture',
    department: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['pmkisan', 'farmers', 'dbt', 'installment', 'ekyc', 'kisan samman nidhi'],
    features: ['Check Beneficiary Payment Status', 'Complete OTP-based / Face eKYC', 'New Farmer Registration', 'Update Aadhaar Name & Bank Details'],
    badge: 'Essential',
  },
  {
    id: 'kisan-suvidha',
    title: 'Kisan Suvidha Portal',
    description: 'Unified agricultural advisory for daily mandi prices, weather forecasts, dealers, plant protection, and farm machinery.',
    url: 'https://kisansuvidha.gov.in/',
    iconName: 'cloud-sun',
    categoryId: 'agriculture',
    department: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['kisan suvidha', 'mandi price', 'weather', 'fertilizers', 'seeds', 'advisory'],
    features: ['Daily Commodity Mandi Rates', '5-Day Hyperlocal Weather Forecast', 'Fertilizer & Seed Dealer Directory', 'Crop Disease Solutions'],
    badge: 'Popular',
  },
  {
    id: 'enam',
    title: 'e-NAM (National Agriculture Market)',
    description: 'Pan-India electronic trading portal networking existing APMC mandis to create a unified national market for commodities.',
    url: 'https://www.enam.gov.in/',
    iconName: 'shopping-cart',
    categoryId: 'agriculture',
    department: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['enam', 'mandi', 'agri trading', 'apmc', 'crop price', 'online auction'],
    features: ['Live Mandi Commodity Auctions', 'Inter-Mandi & Inter-State Trade', 'Quality Assay Reports', 'Direct Bank Settlement for Farmers'],
  },
  {
    id: 'soil-health',
    title: 'Soil Health Card Portal',
    description: 'Soil test-based nutrient recommendations and customized fertilizer dosages to improve soil fertility and crop yield.',
    url: 'https://soilhealth.dac.gov.in/',
    iconName: 'flask-conical',
    categoryId: 'agriculture',
    department: 'Department of Agriculture and Cooperation',
    tags: ['soil health card', 'nutrients', 'fertilizers', 'soil testing', 'agriculture'],
    features: ['Download Soil Health Card PDF', 'Soil Sample Testing Tracking', 'NPK Dosage Guidelines', 'Locate Nearest Soil Testing Lab'],
  },
  {
    id: 'pmfby',
    title: 'PM Fasal Bima Yojana (Crop Insurance)',
    description: 'Comprehensive financial support and insurance cover against non-preventable natural risks from pre-sowing to post-harvest.',
    url: 'https://pmfby.gov.in/',
    iconName: 'umbrella',
    categoryId: 'agriculture',
    department: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['crop insurance', 'fasal bima', 'pmfby', 'drought', 'flood relief', 'claim'],
    features: ['Calculate Crop Insurance Premium', 'Apply for Crop Insurance Policy', 'Report Post-Harvest Crop Loss within 72 hrs', 'Track Insurance Claim Status'],
    badge: 'Popular',
  },
  {
    id: 'mgnrega',
    title: 'MGNREGA Job Card & Muster Roll',
    description: '100 days of guaranteed wage employment in rural areas. Check Job Card status, muster roll attendance, and wage payments.',
    url: 'https://nrega.nic.in/',
    iconName: 'hammer',
    categoryId: 'agriculture',
    department: 'Ministry of Rural Development',
    tags: ['mgnrega', 'nrega', 'job card', 'rural employment', 'muster roll', 'wage payment'],
    features: ['Check Household Job Card Details', 'View Work Allotment & Muster Roll', 'Track DBT Wage Transfer Status', 'Social Audit Reports'],
  },
  {
    id: 'pm-kusum',
    title: 'PM-KUSUM Solar Pump Scheme',
    description: 'Subsidies for farmers to install standalone solar agriculture pumps and solarize existing grid-connected tube wells.',
    url: 'https://pmkusum.mnre.gov.in/',
    iconName: 'sun',
    categoryId: 'agriculture',
    department: 'Ministry of New and Renewable Energy (MNRE)',
    tags: ['pm kusum', 'solar pump', 'renewable energy', 'irrigation', 'subsidy'],
    features: ['Apply for Solar Agricultural Pumps', 'Up to 60% Govt Subsidy on Cost', 'Earn by Selling Solar Power to DISCOMs'],
  },

  // ==========================================
  // HEALTH & AYUSHMAN
  // ==========================================
  {
    id: 'ayushman-abha',
    title: 'Ayushman Bharat ABHA Health ID',
    description: 'Create 14-digit Ayushman Bharat Health Account (ABHA) to digitally store and share medical records and lab reports.',
    url: 'https://abha.abdm.gov.in/',
    iconName: 'heart-pulse',
    categoryId: 'health',
    department: 'National Health Authority (NHA)',
    tags: ['abha', 'health id', 'ayushman bharat', 'digital health', 'medical records'],
    features: ['Create ABHA ID with Aadhaar in 1 Min', 'Link Digital Lab Reports & Prescriptions', 'Consent-based Sharing with Doctors', 'Universal QR Code for Hospital OPD'],
    badge: 'Essential',
  },
  {
    id: 'pmjay-beneficiary',
    title: 'PM-JAY Ayushman Card Portal',
    description: 'Free health insurance cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalisation in empaneled hospitals.',
    url: 'https://beneficiary.nha.gov.in/',
    iconName: 'shield-plus',
    categoryId: 'health',
    department: 'National Health Authority (NHA)',
    tags: ['pmjay', 'ayushman card', '5 lakh insurance', 'cashless hospital', 'health cover'],
    features: ['Check Eligibility (SECC Data / Ration Card)', 'Download Ayushman PVC Card', 'Locate Empaneled Cashless Hospitals', 'Senior Citizens 70+ Universal Coverage'],
    badge: 'Essential',
  },
  {
    id: 'esanjeevani',
    title: 'eSanjeevani Tele-Consultation',
    description: 'Free national telemedicine service to consult certified government doctors and specialist physicians via video call.',
    url: 'https://esanjeevani.mohfw.gov.in/',
    iconName: 'video',
    categoryId: 'health',
    department: 'Ministry of Health and Family Welfare (MoHFW)',
    tags: ['esanjeevani', 'telemedicine', 'doctor consultation', 'free doctor', 'prescription'],
    features: ['Free Online Video Consultation with Doctors', 'Instant Digital Prescription Generation', 'Access to Super-Specialty OPDs', 'No Hospital Queues'],
    badge: 'Popular',
  },
  {
    id: 'janaushadhi',
    title: 'Pradhan Mantri Jan Aushadhi',
    description: 'Locate generic medicine stores providing high quality essential medicines and surgical items at 50% to 90% lower prices.',
    url: 'https://janaushadhi.gov.in/',
    iconName: 'pill',
    categoryId: 'health',
    department: 'Department of Pharmaceuticals',
    tags: ['jan aushadhi', 'generic medicines', 'pharmacy', 'cheap medicine', 'pradhan mantri'],
    features: ['Search Generic Equivalents of Branded Medicines', 'Compare Price Savings Calculator', 'Locate Nearest Kendra Store', 'View 2,000+ Available Medicines'],
    badge: 'Popular',
  },
  {
    id: 'eraktkosh',
    title: 'eRaktKosh Blood Bank Directory',
    description: 'Real-time online blood stock availability across thousands of licensed blood centers and donation camps nationwide.',
    url: 'https://eraktkosh.in/',
    iconName: 'droplet',
    categoryId: 'health',
    department: 'Ministry of Health and Family Welfare',
    tags: ['eraktkosh', 'blood bank', 'blood availability', 'plasma', 'blood donation', 'emergency'],
    features: ['Check Live Blood Group Units Availability', 'Locate Nearby Licensed Blood Banks', 'Register as Voluntary Blood Donor', 'Camp Schedules & Requests'],
  },
  {
    id: 'tele-manas',
    title: 'Tele-MANAS Mental Health Support',
    description: '24x7 free national tele-mental health helpline (14416) providing professional psychological counselling and psychiatric care.',
    url: 'https://telemanas.mohfw.gov.in/',
    iconName: 'smile',
    categoryId: 'health',
    department: 'MoHFW & NIMHANS',
    tags: ['mental health', 'tele manas', 'counselling', 'psychology', 'stress relief', '14416'],
    features: ['24x7 Toll-free Counselling in 20+ Languages', 'Specialized Psychiatric Tele-Consultation', 'Confidential & Safe Support'],
  },

  // ==========================================
  // LAND RECORDS & PROPERTY REGISTRATION
  // ==========================================
  {
    id: 'bhoomi-karnataka',
    title: 'Karnataka Bhoomi Land Records',
    description: 'View and download authentic RTC (Pahani), Mutation register extract, Revenue maps, and Dispute status online.',
    url: 'https://landrecords.karnataka.gov.in/service2/',
    iconName: 'map',
    categoryId: 'land',
    department: 'Revenue Department, Government of Karnataka',
    state: 'Karnataka',
    tags: ['bhoomi', 'pahani', 'rtc', 'mutation', 'karnataka', 'land records'],
    features: ['Download Digitally Signed RTC (Form 16)', 'View Mutation Status & Extract', 'Revenue Village Cadastral Maps', 'Parihara Drought Relief Status'],
    badge: 'Popular',
  },
  {
    id: 'kaveri-karnataka',
    title: 'Karnataka Kaveri Online Services',
    description: 'Online Property valuation, Encumbrance Certificate (EC), Certified Copies (CC), and Deed registration appointments.',
    url: 'https://kaverionline.karnataka.gov.in/',
    iconName: 'building',
    categoryId: 'land',
    department: 'Department of Stamps & Registration, Karnataka',
    state: 'Karnataka',
    tags: ['kaveri', 'ec', 'encumbrance certificate', 'stamp duty', 'property registration'],
    features: ['Download Encumbrance Certificate (EC)', 'Calculate Guidance Value & Stamp Duty', 'Book Registration Slot', 'Download Certified Registered Deeds'],
  },
  {
    id: 'dharani-telangana',
    title: 'Telangana Dharani Integrated Land Portal',
    description: 'Comprehensive portal for agricultural and non-agricultural property transactions, Pattadar Passbook, and slot booking.',
    url: 'https://dharani.telangana.gov.in/',
    iconName: 'compass',
    categoryId: 'land',
    department: 'Registration & Stamps Department, Government of Telangana',
    state: 'Telangana',
    tags: ['dharani', 'telangana', 'pattadar passbook', 'land registry', 'mutation', 'slot booking'],
    features: ['Instant Mutation & Passbook Issuance', 'View Land Details & Cadastral Map', 'Online Registration Slot Booking', 'Prohibited Property Search'],
    badge: 'Popular',
  },
  {
    id: 'up-bhulekh',
    title: 'Uttar Pradesh Bhulekh Portal',
    description: 'Search official Khasra, Khatauni land records, unique plot code (16-digit revenue code), and government land ownership.',
    url: 'https://upbhulekh.gov.in/',
    iconName: 'file-text',
    categoryId: 'land',
    department: 'Board of Revenue, Government of Uttar Pradesh',
    state: 'Uttar Pradesh',
    tags: ['up bhulekh', 'khatauni', 'khasra', 'uttar pradesh', 'land records', 'varasat'],
    features: ['View Certified Khatauni (RoR)', '16-Digit Unique Land Parcel Identifier (ULPIN)', 'Online Varasat (Succession) Filing', 'Disputed Land Status'],
    badge: 'Popular',
  },
  {
    id: 'mahabhulekh',
    title: 'Maharashtra Mahabhulekh (7/12 Online)',
    description: 'Download digitally signed 7/12 (Saat Baara), 8A extract, and Ferfar (Property Card) across all districts of Maharashtra.',
    url: 'https://bhulekh.mahabhumi.gov.in/',
    iconName: 'file-check-2',
    categoryId: 'land',
    department: 'Revenue Department, Government of Maharashtra',
    state: 'Maharashtra',
    tags: ['7/12', 'saat baara', '8a', 'ferfar', 'mahabhulekh', 'maharashtra'],
    features: ['Download Digital 7/12 Extract', 'View 8A Landholding Record', 'Mutation / Ferfar Status', 'City Survey Property Cards'],
    badge: 'Popular',
  },
  {
    id: 'patta-chitta-tn',
    title: 'Tamil Nadu Patta Chitta & FMB',
    description: 'View Patta & FMB extract, verify A-Register status, and check TSLR extract for land parcels in Tamil Nadu.',
    url: 'https://eservices.tn.gov.in/eservicesnew/land/chitta.html',
    iconName: 'map-pinned',
    categoryId: 'land',
    department: 'Revenue Administration, Government of Tamil Nadu',
    state: 'Tamil Nadu',
    tags: ['patta', 'chitta', 'fmb', 'tamil nadu', 'land records', 'a-register', 'tslr'],
    features: ['View Patta / Chitta Extract', 'Verify Government Issued Patta', 'Field Measurement Book (FMB) Sketch', 'Town Survey Land Register (TSLR)'],
  },
  {
    id: 'ap-meebhoomi',
    title: 'Andhra Pradesh Meebhoomi Portal',
    description: 'Search Adangal / Pahani, 1B Records, Village maps, and Electronic Pattadar Passbook for land parcels in AP.',
    url: 'https://meebhoomi.ap.gov.in/',
    iconName: 'layers',
    categoryId: 'land',
    department: 'Revenue Department, Government of Andhra Pradesh',
    state: 'Andhra Pradesh',
    tags: ['meebhoomi', 'adangal', '1b', 'andhra pradesh', 'pattadar passbook', 'fmb'],
    features: ['Download Individual & Village Adangal', 'Search 1-B Record by Survey/Khata Number', 'Download Electronic Passbook (e-PPB)', 'View FMB Village Maps'],
  },
  {
    id: 'bihar-bhumi',
    title: 'Bihar Bhumi & Dakhil Kharij',
    description: 'Online mutation (Dakhil Kharij), view Jamabandi register, LPC (Land Possession Certificate), and pay land revenue tax online.',
    url: 'https://biharbhumi.bihar.gov.in/',
    iconName: 'landmark',
    categoryId: 'land',
    department: 'Department of Revenue and Land Reforms, Bihar',
    state: 'Bihar',
    tags: ['bihar bhumi', 'dakhil kharij', 'jamabandi', 'lpc', 'bhu lagan', 'bihar'],
    features: ['Apply for Online Dakhil Kharij (Mutation)', 'View Digital Jamabandi Register', 'Online Bhu-Lagan (Land Tax) Payment', 'Apply for LPC Certificate'],
  },
  {
    id: 'wb-banglarbhumi',
    title: 'West Bengal Banglarbhumi',
    description: 'Know Your Property (Khatian & Plot information), Mutation application, and RS-LR plot information in West Bengal.',
    url: 'https://banglarbhumi.gov.in/',
    iconName: 'scroll',
    categoryId: 'land',
    department: 'Land & Land Reforms Department, West Bengal',
    state: 'West Bengal',
    tags: ['banglarbhumi', 'khatian', 'plot info', 'west bengal', 'mutation', 'ror'],
    features: ['Search Khatian & Plot Details', 'Online Mutation & Conversion Filing', 'Download Certified RoR Extract', 'Calculate Stamp Duty & Registration Fees'],
  },

  // ==========================================
  // EDUCATION, EXAMS, SKILLS & CAREERS
  // ==========================================
  {
    id: 'swayam',
    title: 'SWAYAM Free Online Courses',
    description: 'Free online certification courses from Class 9 to Post-Graduation delivered by IITs, IIMs, UGC, and NCERT with credit transfer.',
    url: 'https://swayam.gov.in/',
    iconName: 'graduation-cap',
    categoryId: 'education',
    department: 'Ministry of Education (MoE)',
    tags: ['swayam', 'nptel', 'free courses', 'iit courses', 'credit transfer', 'online degree'],
    features: ['Access 3,000+ Free Online Courses', 'Proctored Exam for Recognized Certificates', 'UGC Academic Credit Transfer to University Degree', 'Courses by Top IIT/IIM Faculty'],
    badge: 'Popular',
  },
  {
    id: 'scholarships',
    title: 'National Scholarship Portal (NSP)',
    description: 'One-stop electronic portal for 50+ Central, UGC, AICTE, and State Government scholarship schemes for students.',
    url: 'https://scholarships.gov.in/',
    iconName: 'award',
    categoryId: 'education',
    department: 'Ministry of Electronics and Information Technology (MeitY)',
    tags: ['scholarships', 'nsp', 'student financial aid', 'pre matric', 'post matric', 'ugc scholarship'],
    features: ['Single Common Application Form for All Schemes', 'Direct Benefit Transfer (DBT) into Student Bank', 'OBC, SC, ST & Minority Scholarships', 'Track Application Status Online'],
    badge: 'Essential',
  },
  {
    id: 'abc-apaar',
    title: 'Academic Bank of Credits (APAAR / ABC)',
    description: 'One Nation One Student ID (APAAR ID) to digitally store academic credits earned from higher education institutes.',
    url: 'https://www.abc.gov.in/',
    iconName: 'book-open-check',
    categoryId: 'education',
    department: 'Ministry of Education & DigiLocker',
    tags: ['apaar', 'academic bank of credits', 'abc id', 'student id', 'nep 2020', 'degree credits'],
    features: ['Create Universal 12-Digit APAAR ID', 'Seamless Credit Transfer between Universities', 'Multiple Entry & Exit Support (NEP 2020)', 'Integrated with DigiLocker'],
  },
  {
    id: 'nta-exams',
    title: 'National Testing Agency (NTA)',
    description: 'Official examination portal for JEE Main, NEET UG, CUET, UGC NET, CSIR NET, and other major national entrance exams.',
    url: 'https://nta.ac.in/',
    iconName: 'file-check',
    categoryId: 'education',
    department: 'Department of Higher Education, MoE',
    tags: ['nta', 'jee main', 'neet ug', 'cuet', 'ugc net', 'entrance exam', 'admit card'],
    features: ['Online Registration for Entrance Exams', 'Download Exam Admit Cards & City Intimation', 'View Answer Keys & Question Challenges', 'Check National Percentile & Scorecards'],
    badge: 'Popular',
  },
  {
    id: 'eshram',
    title: 'e-Shram Portal (Unorganised Workers)',
    description: 'National database of unorganized workers with a 12-digit Universal Account Number (UAN) and ₹2 Lakh accidental insurance cover.',
    url: 'https://eshram.gov.in/',
    iconName: 'hard-hat',
    categoryId: 'education',
    department: 'Ministry of Labour and Employment',
    tags: ['eshram', 'labour card', 'unorganized worker', 'uan card', 'insurance', 'migrant worker'],
    features: ['Self-Registration with Aadhaar', 'Download e-Shram Digital Card', '₹2 Lakh Accidental Death/Disability Cover', 'Direct Access to Social Security Schemes'],
    badge: 'Essential',
  },
  {
    id: 'ncs-portal',
    title: 'National Career Service (NCS)',
    description: 'Free employment exchange connecting job seekers with government vacancies, private corporate jobs, and career counsellors.',
    url: 'https://www.ncs.gov.in/',
    iconName: 'briefcase',
    categoryId: 'education',
    department: 'Ministry of Labour and Employment',
    tags: ['jobs', 'ncs', 'career counselling', 'govt jobs', 'job fairs', 'employment exchange'],
    features: ['Search 1,00,000+ Active Verified Job Vacancies', 'Register as Jobseeker or Employer', 'Free Skill Assessment & Career Counselling', 'Online & Offline Job Fairs Information'],
  },
  {
    id: 'udyam-msme',
    title: 'Udyam MSME Registration',
    description: 'Free zero-fee official registration portal for Micro, Small and Medium Enterprises (MSMEs) with paperless certification.',
    url: 'https://udyamregistration.gov.in/',
    iconName: 'factory',
    categoryId: 'education',
    department: 'Ministry of Micro, Small and Medium Enterprises',
    tags: ['udyam', 'msme', 'business registration', 'small business', 'priority sector lending', 'subsidies'],
    features: ['100% Free Zero-Fee Registration', 'Instant Lifetime Udyam Certificate Download', 'Priority Sector Bank Lending Benefits', 'Protection Against Delayed Payments'],
    badge: 'Essential',
  },
  {
    id: 'skill-india',
    title: 'Skill India Digital Hub',
    description: 'AI-enabled digital skill ecosystem offering free certifications, apprenticeship opportunities, and industry training programs.',
    url: 'https://www.skillindiadigital.gov.in/',
    iconName: 'sparkles',
    categoryId: 'education',
    department: 'Ministry of Skill Development and Entrepreneurship',
    tags: ['skill india', 'pmkvy', 'apprenticeship', 'vocational training', 'iti', 'free courses'],
    features: ['Discover 500+ In-demand Skill Courses', 'Apply for Govt Apprenticeship Programs', 'Digitally Verified Skill Credentials', 'Direct Placement Linkage'],
  },
  {
    id: 'vidyalakshmi',
    title: 'Vidya Lakshmi Education Loan',
    description: 'Single window portal for students to search, compare, and apply for educational loans from 40+ nationalized and private banks.',
    url: 'https://www.vidyalakshmi.co.in/',
    iconName: 'landmark',
    categoryId: 'education',
    department: 'Department of Financial Services & MoE',
    tags: ['education loan', 'vidya lakshmi', 'student loan', 'higher studies', 'interest subsidy'],
    features: ['Common Educational Loan Application Form (CELAF)', 'Apply to Multiple Banks Simultaneously', 'Track Loan Processing Status Online', 'Central Sector Interest Subsidy (CSIS)'],
  },

  // ==========================================
  // TRAVEL, TRANSPORT & VEHICLES
  // ==========================================
  {
    id: 'parivahan',
    title: 'Parivahan Sewa (Vehicle RC & Permits)',
    description: 'Vehicle registration details, RC transfer, fitness certificates, road tax payments, and commercial permits nationwide.',
    url: 'https://parivahan.gov.in/parivahan/',
    iconName: 'car',
    categoryId: 'travel',
    department: 'Ministry of Road Transport and Highways (MoRTH)',
    tags: ['parivahan', 'rc', 'vehicle registration', 'road tax', 'vahan', 'morth'],
    features: ['Check Vehicle RC Owner & Status', 'Pay Road Tax Online', 'Apply for Transfer of Ownership (NOC)', 'Duplicate RC & Address Change'],
    badge: 'Essential',
  },
  {
    id: 'sarathi-parivahan',
    title: 'Sarathi (Driving Licence Services)',
    description: 'Apply for new Learner Licence (LL), permanent Driving Licence (DL), renewal, international driving permit, and slot booking.',
    url: 'https://sarathi.parivahan.gov.in/',
    iconName: 'id-card',
    categoryId: 'travel',
    department: 'Ministry of Road Transport and Highways (MoRTH)',
    tags: ['driving licence', 'dl', 'learner licence', 'sarathi', 'dl test slot', 'renew dl'],
    features: ['Contactless Aadhaar-based Online LL Test', 'Apply for Permanent Driving Licence', 'Renew Expired Driving Licence', 'Book RTO Driving Test Slot'],
    badge: 'Essential',
  },
  {
    id: 'irctc',
    title: 'IRCTC Train Ticket Booking',
    description: 'Book confirmed reserved train tickets across Indian Railways, Tatkal quotas, check PNR status, and live running train status.',
    url: 'https://www.irctc.co.in/nget/',
    iconName: 'train',
    categoryId: 'travel',
    department: 'Indian Railway Catering and Tourism Corporation',
    tags: ['irctc', 'train ticket', 'tatkal', 'pnr status', 'indian railways', 'vande bharat'],
    features: ['Reserved & Tatkal Ticket Booking', 'Live PNR Confirmation Probability', 'Flight & Hotel Bookings', 'Meal on Track e-Catering Booking'],
    badge: 'Essential',
  },
  {
    id: 'echallan',
    title: 'e-Challan Digital Traffic System',
    description: 'Check pending traffic violation challans across India using vehicle number or DL, view photographic evidence, and pay fines.',
    url: 'https://echallan.parivahan.gov.in/',
    iconName: 'alert-triangle',
    categoryId: 'travel',
    department: 'Ministry of Road Transport and Highways',
    tags: ['echallan', 'traffic fine', 'challan payment', 'traffic police', 'violation'],
    features: ['Check Pending Traffic Challan Status', 'View Camera / Speed Trap Proof Photos', 'Instant Online Fine Payment', 'Generate Digital Payment Receipt'],
    badge: 'Popular',
  },
  {
    id: 'rail-madad',
    title: 'Rail Madad (Train & Station Grievance)',
    description: '24x7 integrated Indian Railways portal to register instant complaints for medical emergency, cleanliness, coach amenities, and safety.',
    url: 'https://railmadad.indianrailways.gov.in/',
    iconName: 'life-buoy',
    categoryId: 'travel',
    department: 'Ministry of Railways (Helpline: 139)',
    tags: ['rail madad', 'railway complaint', '139', 'train cleanliness', 'security on train'],
    features: ['Real-time Grievance Tracking with PNR', 'Medical Assistance on Running Train', 'Coach Cleanliness & AC Issue Resolution', 'Lost Baggage Tracking'],
    badge: 'Popular',
  },
  {
    id: 'digiyatra',
    title: 'Digi Yatra (Facial Biometric Boarding)',
    description: 'Contactless, paperless facial biometric check-in at major Indian airports for seamless entry without physical boarding passes.',
    url: 'https://www.digiyatra.com/',
    iconName: 'scan-face',
    categoryId: 'travel',
    department: 'Digi Yatra Foundation / Ministry of Civil Aviation',
    tags: ['digiyatra', 'airport', 'boarding pass', 'facial recognition', 'contactless travel', 'flight'],
    features: ['Fast-track Priority Airport Gate Entry', 'Paperless Security Checkpoints', 'Self-Sovereign Identity Protection'],
  },
  {
    id: 'airsewa',
    title: 'AirSewa Passenger Grievance',
    description: 'Official Ministry of Civil Aviation portal for flight refund complaints, lost baggage, flight delays, and airline passenger rights.',
    url: 'https://airsewa.gov.in/',
    iconName: 'plane-takeoff',
    categoryId: 'travel',
    department: 'Ministry of Civil Aviation',
    tags: ['airsewa', 'flight refund', 'lost luggage', 'dgca', 'passenger rights', 'airline complaint'],
    features: ['Lodge Complaint Against Airlines & Airports', 'Check Flight Delay Compensations', 'Track Resolution by DGCA Officers'],
  },

  // ==========================================
  // UTILITIES, SAFETY & LAW
  // ==========================================
  {
    id: 'cybercrime',
    title: 'National Cyber Crime Reporting Portal',
    description: 'Report financial fraud, identity theft, unauthorized SIMs, cyber blackmail, and phishing scams. Toll-free helpline 1930.',
    url: 'https://cybercrime.gov.in/',
    iconName: 'shield-alert',
    categoryId: 'utilities',
    department: 'Indian Cyber Crime Coordination Centre (I4C), MHA',
    tags: ['cyber crime', '1930', 'online fraud', 'upi fraud', 'cyber police', 'hack'],
    features: ['Instant Reporting of Financial Fraud (Helpline 1930)', 'Freeze Defrauded Bank Accounts in Golden Hour', 'Report Cyber Harassment Anonymously', 'Track Investigation Progress'],
    badge: 'Essential',
  },
  {
    id: 'sancharsaathi',
    title: 'Sanchar Saathi (Block Stolen Phones)',
    description: 'Block lost/stolen mobile phones across all telecom networks (CEIR), and check all mobile numbers registered in your name (TAFCOP).',
    url: 'https://sancharsaathi.gov.in/',
    iconName: 'smartphone-charging',
    categoryId: 'utilities',
    department: 'Department of Telecommunications (DoT)',
    tags: ['sanchar saathi', 'lost phone', 'ceir', 'block imei', 'tafcop', 'unauthorized sim'],
    features: ['Block Stolen Phone IMEI across Pan-India Telecoms', 'Unblock Phone when Recovered', 'Check All Mobile Numbers Linked to your Aadhaar (TAFCOP)', 'Know Your Mobile Handset Authenticity'],
    badge: 'Essential',
  },
  {
    id: 'ecourts',
    title: 'eCourts Services (Case Status)',
    description: 'Search case status, daily cause lists, court orders, and judgments across High Courts, District Courts, and Subordinate Courts.',
    url: 'https://services.ecourts.gov.in/',
    iconName: 'scale',
    categoryId: 'utilities',
    department: 'e-Committee, Supreme Court of India / DoJ',
    tags: ['ecourts', 'case status', 'court order', 'high court', 'district court', 'cause list', 'judgments'],
    features: ['Search Case by CNR Number / Party Name', 'Download Certified Judicial Orders & Judgments', 'Daily Court Cause Lists', 'Track Next Hearing Date'],
    badge: 'Popular',
  },
  {
    id: 'pmsuryaghar',
    title: 'PM Surya Ghar (Free Solar Electricity)',
    description: 'Government subsidy of up to ₹78,000 for installing residential rooftop solar systems to get up to 300 units free electricity monthly.',
    url: 'https://pmsuryaghar.gov.in/',
    iconName: 'sun-medium',
    categoryId: 'utilities',
    department: 'Ministry of New and Renewable Energy',
    tags: ['pm surya ghar', 'rooftop solar', 'free electricity', 'solar subsidy', 'solar panel'],
    features: ['Direct Govt Subsidy (up to ₹78,000 in bank account)', 'Select Certified Local Solar Vendors', 'Calculate Electricity Savings', 'Net Metering Integration with DISCOM'],
    badge: 'Popular',
  },
  {
    id: 'indane-lpg',
    title: 'Indane / IndianOil LPG Portal',
    description: 'Book LPG refill cylinders online, check cylinder subsidy status, apply for new connection, and transfer distributor.',
    url: 'https://cx.indianoil.in/',
    iconName: 'flame',
    categoryId: 'utilities',
    department: 'Indian Oil Corporation Limited (IOCL)',
    tags: ['indane', 'lpg booking', 'gas cylinder', 'iocl', 'subsidy', 'indane gas'],
    features: ['Instant LPG Refill Booking', 'Track Delivery Boy Status', 'Apply for New Double Bottle Connection', 'Change Distributor Online'],
  },
  {
    id: 'hp-gas',
    title: 'HP Gas (My HP Gas Portal)',
    description: 'Online booking and payment for HP Gas cylinders, surrender connection, apply for PM Ujjwala subsidy, and book mechanic.',
    url: 'https://myhpgas.in/',
    iconName: 'zap',
    categoryId: 'utilities',
    department: 'Hindustan Petroleum Corporation Limited (HPCL)',
    tags: ['hp gas', 'my hpgas', 'cylinder booking', 'hpcl', 'gas subsidy'],
    features: ['Refill Booking with Online Payment', 'Opt-out of LPG Subsidy (GiveItUp)', 'Surrender / Transfer Connection'],
  },
  {
    id: 'indiapost',
    title: 'India Post Tracking & Services',
    description: 'Track Speed Post consignments, calculate parcel postage, search PIN codes, and access Post Office Savings Bank (POSB) accounts.',
    url: 'https://www.indiapost.gov.in/',
    iconName: 'mail',
    categoryId: 'utilities',
    department: 'Department of Posts, Ministry of Communications',
    tags: ['india post', 'speed post tracking', 'pin code', 'post office savings', 'postal life insurance'],
    features: ['Live Speed Post & Registered Article Tracking', 'Official National PIN Code Search Directory', 'Calculate Domestic & International Postage', 'Post Office Monthly Income Scheme (POMIS) Details'],
  },
  {
    id: 'nalsa-legal',
    title: 'NALSA (Free Legal Aid for Citizens)',
    description: 'Free legal aid services and representation for economically weaker sections, women, children, and victims of injustice.',
    url: 'https://nalsa.gov.in/',
    iconName: 'gavel',
    categoryId: 'utilities',
    department: 'National Legal Services Authority',
    tags: ['free legal aid', 'nalsa', 'lawyer', 'legal counsel', 'lok adalat', 'justice'],
    features: ['Apply for Free Legal Aid Lawyer', 'National Lok Adalat Settlements', 'Victim Compensation Assistance'],
  },

  // ==========================================
  // HOUSING & WELFARE SCHEMES
  // ==========================================
  {
    id: 'pmay-urban',
    title: 'Pradhan Mantri Awas Yojana (PMAY Urban)',
    description: 'Credit Linked Subsidy Scheme (CLSS) and affordable housing assistance for eligible urban middle class and EWS families.',
    url: 'https://pmay-urban.gov.in/',
    iconName: 'home',
    categoryId: 'welfare',
    department: 'Ministry of Housing and Urban Affairs',
    tags: ['pmay', 'awas yojana', 'housing subsidy', 'clss', 'home loan interest subsidy', 'affordable housing'],
    features: ['Check Beneficiary Name & Approval Status', 'Apply for Interest Subsidy under PMAY-U', 'Track Geo-tagged Construction Progress', 'Locate Affordable Housing Projects'],
    badge: 'Essential',
  },
  {
    id: 'pmay-gramin',
    title: 'PMAY Gramin (Rural Housing)',
    description: 'Financial assistance of up to ₹1.20 Lakh to construct pucca houses with hygienic cooking spaces in rural areas.',
    url: 'https://pmayg.nic.in/',
    iconName: 'building',
    categoryId: 'welfare',
    department: 'Ministry of Rural Development',
    tags: ['pmayg', 'rural housing', 'gramin awas', 'housing grant', 'pucca house'],
    features: ['Check Gramin Beneficiary Waitlist', 'View Stage-wise Direct DBT Installments', 'Geo-tagged House Photos Upload'],
  },
  {
    id: 'udid-disability',
    title: 'UDID Card (Unique Disability ID)',
    description: 'Universal ID card and disability certificate for persons with disabilities (Divyangjan) for national welfare and travel concessions.',
    url: 'https://www.swavlambancard.gov.in/',
    iconName: 'accessibility',
    categoryId: 'welfare',
    department: 'Department of Empowerment of Persons with Disabilities',
    tags: ['udid', 'disability card', 'divyangjan', 'railway concession', 'swavlamban'],
    features: ['Apply for Unique Disability ID Card (UDID)', 'Download Digital Disability Certificate', 'National Validity across All States & Railways', 'Track Medical Assessment Date'],
    badge: 'Popular',
  },
  {
    id: 'pm-ujjwala',
    title: 'PM Ujjwala Yojana (Free LPG)',
    description: 'Free deposit-free LPG connection along with first refill and stove for women from low-income households.',
    url: 'https://pmuy.gov.in/',
    iconName: 'flame',
    categoryId: 'welfare',
    department: 'Ministry of Petroleum and Natural Gas',
    tags: ['ujjwala', 'free gas', 'pmuy', 'women welfare', 'lpg subsidy'],
    features: ['Apply for New Ujjwala 2.0 Connection', 'Check Eligibility Criteria', 'Zero Security Deposit Required'],
  },
  {
    id: 'nsap-pension',
    title: 'National Social Assistance (NSAP Pension)',
    description: 'Social security pensions for elderly citizens (IGNOAPS), widows (IGNWPS), and persons with severe disabilities (IGNDPS).',
    url: 'https://nsap.nic.in/',
    iconName: 'heart-handshake',
    categoryId: 'welfare',
    department: 'Ministry of Rural Development',
    tags: ['old age pension', 'widow pension', 'nsap', 'social assistance', 'dbt pension'],
    features: ['Check National Pension Beneficiary Status', 'Direct Monthly DBT Bank Credit', 'Apply for National Social Security Aid'],
  },
  {
    id: 'jal-jeevan',
    title: 'Jal Jeevan Mission Dashboard',
    description: 'National mission providing safe and adequate tap water connections to every rural household (Har Ghar Jal).',
    url: 'https://ejalshakti.gov.in/jjmreport/JJMIndia.aspx',
    iconName: 'waves',
    categoryId: 'welfare',
    department: 'Department of Drinking Water and Sanitation, Ministry of Jal Shakti',
    tags: ['jal jeevan mission', 'tap water', 'har ghar jal', 'water supply', 'village water'],
    features: ['View Village Tap Water Coverage Dashboard', 'Water Quality Testing Laboratory Reports', 'Report Water Supply Outages'],
  },
];

export const HELPLINES_DATA: Helpline[] = [
  {
    id: 'national-emergency',
    name: 'National Emergency Response',
    number: '112',
    description: 'Unified single number for Police, Fire, and Ambulance emergency across India.',
    category: 'Emergency',
    iconName: 'shield-alert',
    badge: 'All-in-One 24x7',
  },
  {
    id: 'cyber-fraud',
    name: 'Cyber Financial Fraud',
    number: '1930',
    description: 'Immediate reporting of unauthorized bank/UPI transactions to freeze defrauded funds.',
    category: 'Cyber Safety',
    iconName: 'phone-call',
    badge: 'Golden Hour Rapid Response',
  },
  {
    id: 'women-helpline',
    name: 'Women in Distress Helpline',
    number: '1091',
    description: '24x7 emergency response, legal counsel, and rescue support for women in distress.',
    category: 'Women & Child',
    iconName: 'shield-check',
    badge: 'Toll-free 24x7',
  },
  {
    id: 'childline',
    name: 'National Childline',
    number: '1098',
    description: 'Emergency assistance, rescue, and protection for children in need of care.',
    category: 'Women & Child',
    iconName: 'heart',
    badge: 'Toll-free 24x7',
  },
  {
    id: 'rail-madad-helpline',
    name: 'Rail Madad Security & Help',
    number: '139',
    description: 'Integrated Indian Railways helpline for medical emergency, theft, AC/coach complaints.',
    category: 'Travel & Transport',
    iconName: 'train',
    badge: '12 Languages 24x7',
  },
  {
    id: 'kisan-call-center',
    name: 'Kisan Call Centre',
    number: '1800-180-1551',
    description: 'Free expert agricultural advice on crops, fertilizers, pest control, and market rates.',
    category: 'Agriculture',
    iconName: 'sprout',
    badge: '6 AM to 10 PM',
  },
  {
    id: 'lpg-emergency',
    name: 'LPG Gas Leak Emergency',
    number: '1906',
    description: 'Dedicated national emergency response for cooking gas leakage and cylinder fire hazards.',
    category: 'Emergency',
    iconName: 'flame',
    badge: 'Immediate Dispatch 24x7',
  },
  {
    id: 'covid-health',
    name: 'National Health & Tele-MANAS',
    number: '14416',
    description: 'National tele-mental health consultation, psychological support, and health guidance.',
    category: 'Health',
    iconName: 'heart-pulse',
    badge: 'Free Consultation',
  },
  {
    id: 'senior-citizens',
    name: 'Elder Line (Senior Citizens)',
    number: '14567',
    description: 'Free national helpline for senior citizens offering emotional support, rescue, and legal aid.',
    category: 'Welfare',
    iconName: 'users',
    badge: 'Toll-free 8 AM - 8 PM',
  },
  {
    id: 'consumer-helpline',
    name: 'National Consumer Helpline',
    number: '1915',
    description: 'Register consumer complaints against e-commerce fraud, deceptive ads, and warranty issues.',
    category: 'Citizen Rights',
    iconName: 'scale',
    badge: 'Govt NCH',
  },
];

export const POPULAR_SEARCH_TAGS = [
  'Aadhaar Download',
  'Income Tax ITR',
  'DigiLocker',
  'Passport Seva',
  'PM Kisan',
  'Driving Licence',
  '7/12 & Bhulekh',
  'Ayushman Card',
  'Vehicle RC',
  'EPFO PF Balance',
  'Udyam MSME',
  'Free Solar Rooftop',
];

export const STATE_LIST = [
  'All States',
  'Andhra Pradesh',
  'Bihar',
  'Delhi',
  'Gujarat',
  'Karnataka',
  'Madhya Pradesh',
  'Maharashtra',
  'Rajasthan',
  'Tamil Nadu',
  'Telangana',
  'Uttar Pradesh',
  'West Bengal',
];
